const Websitepackagedata = [
    {
        id: 'webbasic',
        packageTitle: 'Basic Website Design',
        originalPrice: '$598',
        discountPrice: '$149',
        details: [
            '3 Page Business Website',
            '5 Revisions',
            'Complete Deployment',
            'Dedicated Designer',
            'Dedicated Professional Developer',
            'Dedicated Account Manager',
            '2 Stock Images',
            'Complete W3C Certified HTML',
            'Google Optimised Sitemap',
            '48 to 72 hours TAT',
            'FREE Domain & Hosting',
            'Features:',
            '100% Ownership Rights',
            '100% Satisfaction Guaranteed',
            '100% Unique Design Guarantee',
            '100% Money Back Guarantee',
            'All Final File Formats',
          ],
    },
    {
        id: 'webstartup',
        packageTitle: 'Startup Website Design',
        originalPrice: '$1,198',
        discountPrice: '$799',
        details: [
                '5 Unique Business Pages Website',
                'Unlimited Revisions',
                'Complete Deployment',
                '2 Dedicated Designer',
                'Dedicated Professional Developer',
                'Dedicated Account Manager',
                '3 Stock Images',
                'Complete W3C Certified HTML',
                'Google Optimised Sitemap',
                '48 to 72 hours TAT',
                'FREE Domain &amp; Hosting',
                'Features:',
                '100% Ownership Rights',
                '100% Satisfaction Guaranteed',
                '100% Unique Design Guarantee',
                '100% Money Back Guarantee',
                'All Final File Formats',
                'Add-Ons:',
                'Mobile Responsive will be charged additionally',
                'CMS will be Charged Additionally',
          ],
    },
    {
        id: 'webprofessional',
        packageTitle: 'Professional Website Design',
        originalPrice: '$1,648',
        discountPrice: '$1,099',
        details: [
                '10 Unique Business Pages Website',
                'Unlimited Revisions',
                'Complete Deployment',
                '4 Dedicated Designer', 
                'Dedicated Professional Developer', 
                'Dedicated Account Manager',
                '5 Stock Images',
                'Complete W3C Certified HTML',
                'Google Optimised Sitemap',
                '48 to 72 hours TAT',
                'FREE Domain &amp; Hosting',
                'Features:',
                '100% Ownership Rights',
                '100% Satisfaction Guaranteed',
                '100% Unique Design Guarantee',
                '100% Money Back Guarantee',
                'All Final File Formats',
                'Add-Ons:',
                'Mobile Responsive will be charged additionally',
          ],
    },
    {
        id: 'ecommercebasic',
        packageTitle: 'Startup E-Commerce Website Design',
        originalPrice: '$799',
        discountPrice: '$599',
        details: [
            'Customized Design',
            'Up-to 100 Products',
            'Content Management System (CMS)',
            'Mini shopping Integration',
            'Payment Module Integration',
            'Easy Product Search',
            'Dedicated designer &amp; developer',
            'Unlimited Revisions',
          ],
    },
    {
        id: 'ecommercepro',
        packageTitle: 'Professional E-Commerce Website Design',
        originalPrice: '$900',
        discountPrice: '$830',
        details: [
            'Customized Design',
            'Up-to 500 Products',
            'Content Management System (CMS)',
            'Full Shopping Cart Integration',
            'Payment Module Integration',
            'Easy Product Search',
            'Unlimited Revisions',
            'Product Reviews',
            '5 Professional Banner',
            'Dedicated Designers',
            'Dedicated Developers',
          ],
    },
    {
        id: 'ecommerceelite',
        packageTitle: 'Elite E-Commerce Website Design',
        originalPrice: '$3500',
        discountPrice: '$2900',
        details: [
            'UNLIMITED Logo Design Concepts',
            'By 6 Award Winning Designers',
            'Icon Design',
            'UNLIMITED Revisions',
            'Print Media',
            'Stationary Design (BusinessCard,Letterhead & Envelope)',
            'Invoice Design, Email Signature',
            'Bi-Fold Brochure (OR) 2 Sided Flyer Design',
            'Product Catalog Design',
            'Sign age Design (OR) Label Design',
            'T-Shirt Design (OR) Car Wrap Design',
            'Website',
            'E-Commerce Store Design',
            'Product Detail Page Design',
            'Unique Banner Slider',
            'Featured Products Showcase',
            'Full Shopping Cart Integration',
            'Unlimited Products',
            'Unlimited Categories',
            'Product Rating &amp; Reviews',
            'Easy Product Search',
            'Payment Gateway Integration',
            'Multi-currency Support',
            'Content Management System',
            'Cutomer Log-in Area',
            'Mobile Responsive',
            'Social Media Plugins Integration',
            'Tell a Friend Feature',
            'Social Media Pages',
            'Facebook , Twitter, YouTube, Google+ &amp; Pinterest Page Designs',
          ],
    },
];

export default Websitepackagedata